### ISSUE TITLE
Create front-end application HTML

### ISSUE THREAD

**Issue by PatrickBruso** [CSSG-Labs/flask-todo-app#18]
Create the backbones of the front-end application by creating the home page HTML (don't worry about CSS yet).  Create the forms, inputs, and submits for the to-do app based on the mockup created by ironbe on the discord channel.

![flask-todo-figma-mockup-v1](https://user-images.githubusercontent.com/1243803/162647546-a9495aec-fda0-4e61-b493-604a8a7b07fd.png)

**Comment by PatrickBruso** [comment]
> I can do this. Do you still need someone to help?

Hi Joel,
Andromedamoon-stack is currently working on this issue.  Once the HTML is completed, we will need someone to work on the CSS to align the HTML objects to match the mockup.  If that's something you're interested in, you could work on that.

**Comment by PatrickBruso** [comment]
> I can do this. Do you still need someone to help?

Hi Joel,

I added a new issue for creating a registration page in HTML if you want to take a crack at that.

**Comment by Joel-Pearce** [comment]
Yep, will do in a moment.

**Comment by riboney** [comment]
Duplicate Issue. Issue is address in PR #31
