### ISSUE TITLE
unable to connect to server and db

### ISSUE THREAD

**Issue by fidel-bello** [CSSG-Labs/flask-todo-app#29]
**Describe the bug**
_..._  Hi.. is there something I'm missing? the code looks good but i am unable to connect to the database and server

**To Reproduce**
_..._ run the app

**Expected behavior**
_..._ importError

**Screenshots**
![image](https://user-images.githubusercontent.com/73322116/167284056-9325a3b7-ba77-4a2e-8a59-d285f60eee4c.png)

**Additional context**
i have installed all requirements and also the command..  flask init -db .. How does that work? i tried it and it is unrecognized

**Comment by fidel-bello** [comment]
![image](https://user-images.githubusercontent.com/73322116/167285050-126d5d6b-0b67-436c-b8b8-c95d08b05d58.png)
my env

**Comment by riboney** [comment]
> ![image](https://user-images.githubusercontent.com/73322116/167285050-126d5d6b-0b67-436c-b8b8-c95d08b05d58.png) my env

What is this screenshot showing?

**Comment by fidel-bello** [comment]
thanks for the video
![image](https://user-images.githubusercontent.com/73322116/167304735-4ed48039-b1d8-4943-9d3b-6e3ac155c738.png)
